name: 'breast_cancer_env'
channels:
    - conda-forge
    - defaults
dependencies:
    - ipykernel
    - pandas
    - r-base
    - r-tidyverse
    - r-shiny
    - r-languageserver
    - r-plotly
    - r-tidyr
    - r-dplyr
    - r-ggplot2
    - r-readr


